export const codeString = [
  "Mass_Files_Store_Bot_Mn3P6B7hgAG8YJUW",
  "Mass_Files_Store_Bot_xYa__JZqpssYG4w_",
  "Mass_Files_Store_Bot_I_8E8i80kdCO8TUa",
  "Mass_Files_Store_Bot_mEvAeaTdvsAaSycU",
  "Mass_Files_Store_Bot__1ZQInQJnCWFP59L",
  "Mass_Files_Store_Bot_JqPwA07l7CQ6AUWo",
  "Mass_Files_Store_Bot_H7kJQ7Aj5WAXLfWS",
  "Mass_Files_Store_Bot_vltXF7sEpoDxFMLE",
  "Mass_Files_Store_Bot_CU2Pcu1Bemei6F5Q",
  "Mass_Files_Store_Bot_7cym1HwfcV5GAFUg",
  "Mass_Files_Store_Bot_tzNCuZF3c9T7fkkh",
  "Mass_Files_Store_Bot_ExUEMXg9AR7Uj5_S",
  "Mass_Files_Store_Bot_ceXqqNnVF9DAL3c0",
  "Mass_Files_Store_Bot_ILqtKrPz9uz3VYl1",
  "Mass_Files_Store_Bot_nCHIOb84BtVy5BMS",
  "Mass_Files_Store_Bot_gV3fvuSWQ53OQMzT",
  "Mass_Files_Store_Bot_5qK6NjsXxQtgjP0T"
];
