export const codeString = [
  "wenjianjibot_1v_lYFLMYNF9kwi7F5c",
  "wenjianjibot_1d_c5L9UgU9pXC7lDNq",
  "wenjianjibot_1v_DAjF0EKIGuQrJ4Wk",
  "wenjianjibot_1p_AkWyYg6zHlQnz0UP",
  "wenjianjibot_1v_NlxORQx0KymDcBkq",
  "wenjianjibot_2v_3FucMcW9NtOctj6q",
  "wenjianjibot_2v_h4zLO60cVLqKzK46",
  "wenjianjibot_1v_H3yvvuPT9cf1pTdH",
  "wenjianjibot_1p_4xvieoWtvPiyTQdT",
  "wenjianjibot_1v_tU7Z4lJvyAtihk4e",
  "wenjianjibot_5v_HSirt5to1w7uRHFj",
  "wenjianjibot_1v_IgFR99rJE8s5yLZb",
  "wenjianjibot_1v_lmIDg8ifOKgc1urD",
  "wenjianjibot_1v_Ue7jeZ6K0R2qG9Pb",
  "wenjianjibot_4p_lNQURa5Pil56e9lq",
  "wenjianjibot_8p_sUTJeywtV2L7NpeH",
  "wenjianjibot_5v_HETbX3ardaPN4xGs"
];