export const botString = {
  "0": "",
  "1": "qqfile",
  // "2": "lockhive",
  "2": "fileport",
  "3": "xiumi",
  "4": "wenjianji",
  "5": "zyxfiles",
  "6": "aotem",
  "7": "jiematop",
  "8": "uujie",
  "9": "safsadf",
  "10": "kodexfiles2",
  "11": "lunindiacipoksupretto",
  "12": "paniang",
  "13": "ryumasepongmilku",
  "14": "fileshubro",
  "15": "filespanindo",
  "16": "hijautebal",
  "17": "kodexchatsind",
  "18": "massfilesstore",
  "19": "steviarchiver",
};