export const botString = {
  "0": "",
  "1": "qqfile",
  // "2": "lockhive",
  "2": "aotem",
  "3": "jiematop",
  "4": "uujie",
  "5": "safsadf",
  "6": "kodexfiles2",
  "7": "lunindiacipoksupretto",
  "8": "paniang",
  "9": "ryumasepongmilku",
  "10": "fileshubro",
  "11": "filespanindo",
  "12": "hijautebal",
  "13": "kodexchatsind",
  "14": "massfilesstore",
  "15": "steviarchiver",
  "16": "fileport",
  "17": "jsfile",
  "18": "kfcmnb",
  "19": "messenger",
  "20": "palucode",
  "21": "siren",
  "22": "tebiejie",
  "23": "xiumi",
  "24": "wenjianji",
  "25": "zyxfiles",
};