export const botString = {
  "0": "",
  "1": "qqfile",
  // "2": "lockhive",
  "2": "fileport",
  "3": "uujie",
  "4": "xiumi",
  "5": "zyxfiles",
  "6": "kodexfiles2",
  "7": "ryumasepongmilku",
  "8": "lunindiacipoksupretto",
  "9": "hijautebal",
  "10": "fileshubro",
  "11": "filespanindo",
  "12": "kodexchatsind",
  "13": "massfilesstore",
  "14": "steviarchiver",
};